[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; connect-src 'self' https://api.textinghouse.com;"

[[redirects]]
  from = "https://www.shenyukeji.cc/*"
  to = "https://shenyukeji.cc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.shenyukeji.cc/*"
  to = "https://shenyukeji.cc/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://shenyukeji.cc/*"
  to = "https://shenyukeji.cc/:splat"
  status = 301
  force = true